/**
 * Migration 037: Force Fix Measurement/Time Semantic Concepts (4.S19)
 *
 * Updates semantic concepts for measurement/time fields based on field name,
 * regardless of what concept they currently have. This ensures fields match
 * the concepts generated by ExpandedConceptBuilder (space-separated format).
 *
 * This is a follow-up to migration 036, which only updated concepts that matched
 * specific patterns. This migration updates ALL matching fields regardless of
 * their current concept value.
 */

DO $$
DECLARE
  rec RECORD;
  updated_count INTEGER := 0;
BEGIN
  -- Update concepts based on field name (regardless of current concept value)
  FOR rec IN
    SELECT *
    FROM (VALUES
      ('rpt.Measurement', 'areaReduction', 'area reduction', 0.95),
      ('rpt.Measurement', 'area', 'area', 0.9),
      ('rpt.Measurement', 'baselineArea', 'baseline area', 0.9),
      ('rpt.Measurement', 'percentChange', 'percent change', 0.9),
      ('rpt.Measurement', 'reduction', 'reduction', 0.85),
      ('rpt.Measurement', 'measurementDate', 'measurement date', 0.9),
      ('rpt.Measurement', 'daysFromBaseline', 'days from baseline', 0.85),
      ('rpt.Assessment', 'assessmentDate', 'assessment date', 0.9),
      ('rpt.Assessment', 'baselineDate', 'baseline date', 0.9),
      ('rpt.Assessment', 'startDate', 'start date', 0.85),
      ('rpt.Assessment', 'endDate', 'end date', 0.85),
      -- Also handle baselineDate in rpt.Wound (if it exists there)
      ('rpt.Wound', 'baselineDate', 'baseline date', 0.9),
      ('rpt.Wound', 'depth', 'wound depth', 0.85),
      ('rpt.Wound', 'length', 'wound length', 0.85),
      ('rpt.Wound', 'width', 'wound width', 0.85),
      ('rpt.Wound', 'volume', 'wound volume', 0.85),
      ('rpt.Wound', 'woundState', 'wound status', 0.85),
      ('rpt.Wound', 'healingStatus', 'healing status', 0.85),
      -- Fields that exist in rpt.Measurement but have wrong concepts
      ('rpt.Measurement', 'depth', 'wound depth', 0.85),
      ('rpt.Measurement', 'length', 'wound length', 0.85),
      ('rpt.Measurement', 'width', 'wound width', 0.85),
      ('rpt.Measurement', 'volume', 'wound volume', 0.85),
      -- Alternative field names (dimDateFk might be the date field)
      ('rpt.Measurement', 'dimDateFk', 'measurement date', 0.85),
      ('rpt.Assessment', 'date', 'assessment date', 0.9),
      ('rpt.Assessment', 'dimDateFk', 'assessment date', 0.85),
      -- WoundState table fields
      ('rpt.WoundState', 'startDate', 'start date', 0.85),
      ('rpt.WoundState', 'endDate', 'end date', 0.85),
      -- Fields that exist in rpt.Measurement but have wrong concepts
      ('rpt.Measurement', 'depth', 'wound depth', 0.85),
      ('rpt.Measurement', 'length', 'wound length', 0.85),
      ('rpt.Measurement', 'width', 'wound width', 0.85),
      ('rpt.Measurement', 'volume', 'wound volume', 0.85),
      -- Alternative field names (dimDateFk might be the date field)
      ('rpt.Measurement', 'dimDateFk', 'measurement date', 0.85),
      ('rpt.Assessment', 'date', 'assessment date', 0.9),
      ('rpt.Assessment', 'dimDateFk', 'assessment date', 0.85),
      -- WoundState table fields
      ('rpt.WoundState', 'startDate', 'start date', 0.85),
      ('rpt.WoundState', 'endDate', 'end date', 0.85)
    ) AS t(table_name, column_name, new_concept, confidence)
  LOOP
    -- Update ALL rows matching table_name + column_name, regardless of current concept
    -- Store old concept in metadata for audit trail
    UPDATE "SemanticIndexNonForm" n
    SET
      semantic_concept = rec.new_concept,
      confidence = GREATEST(n.confidence, rec.confidence), -- Keep higher confidence
      metadata = COALESCE(n.metadata, '{}'::jsonb) || jsonb_build_object(
        'concept_fixed_by', '037_force_fix_measurement_field_concepts',
        'previous_concept', n.semantic_concept,
        'fixed_at', NOW()
      )
    WHERE n.table_name = rec.table_name
      AND n.column_name = rec.column_name
      AND n.semantic_concept IS DISTINCT FROM rec.new_concept; -- Only update if different
    
    GET DIAGNOSTICS updated_count = ROW_COUNT;
    
    IF updated_count > 0 THEN
      RAISE NOTICE 'Updated % rows: %.% to "%"', 
        updated_count, rec.table_name, rec.column_name, rec.new_concept;
    END IF;
  END LOOP;

  RAISE NOTICE 'Migration 037 completed: Force-updated semantic concepts for measurement/time fields';
END $$;

-- Verification: Check that concepts are now correct
-- SELECT table_name, column_name, semantic_concept, confidence
-- FROM "SemanticIndexNonForm"
-- WHERE column_name IN ('areaReduction', 'baselineDate', 'healingStatus', 'measurementDate', 'depth')
-- ORDER BY table_name, column_name;

